Contoso.Events.Web/Controllers/HomeController.cs
using Contoso.Events.Models;
using Contoso.Events.ViewModels;
using Microsoft.ServiceBus;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.Web.Mvc;

namespace Contoso.Events.Web.Controllers
{
    public class HomeController : Controller
    {
        private const int EVENTS_GRID_SIZE = 10;
        
        public ActionResult Index()
        {
            UpcomingEventsViewModel viewModel = new UpcomingEventsViewModel();

            return View(viewModel);
        }

        public ActionResult Events(int? id)
        {
            EventsGridViewModel viewModel = new EventsGridViewModel(
                pageSize: EVENTS_GRID_SIZE,
                currentPage: id ?? 1
            );

            return View(viewModel);
        }

        public ActionResult Event(string id)
        {
            EventViewModel viewModel = null;

            if (!String.IsNullOrEmpty(id))
            {
                viewModel = new EventViewModel(
                    eventKey: id
                );
            }

            if (viewModel == null)
            {
                return new HttpNotFoundResult();
            }

            return View(viewModel);
        }

        public ActionResult Register(string id)
        {
            RegisterViewModel viewModel = null;

            if (!String.IsNullOrEmpty(id))
            {
                viewModel = new RegisterViewModel(
                    eventKey: id
                );
            }

            if (viewModel == null)
            {
                return new HttpNotFoundResult();
            }

            return View(viewModel);
        }

        public ActionResult Registered(Guid? id)
        {
            return View(id);
        }        
    }
}

Contoso.Events.Web/Controllers/RegisterController.cs
using Contoso.Events.ViewModels;
using Contoso.Events.ViewModels.Dynamic;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using Newtonsoft.Json.Linq;
using System;
using System.Configuration;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;

namespace Contoso.Events.Web.Controllers
{
    public class RegisterController : ApiController
    {
        public dynamic Post(JToken registrationToken)
        {
            dynamic registration = DynamicEntity.GenerateDynamicItem(registrationToken);

            Guid registrationKey = StoreRegistration(registration);

            UpdateEventRegistrationCount(registrationToken);

            if (RoleEnvironment.IsAvailable)
            {
                var response = Request.CreateResponse(HttpStatusCode.Moved);
                var url = Url.Route("Default", new { controller = "Home", action = "Registered", id = registrationKey });
                response.StatusCode = HttpStatusCode.Redirect;
                response.Headers.Location = new Uri(ToAbsoluteUrl(url), UriKind.Absolute);
                return response;
            }
            else
            {
                return RedirectToRoute("Default", new { controller = "Home", action = "Registered", id = registrationKey });
            }
        }

        private Guid StoreRegistration(dynamic registration)
        {
            var storageAccount = Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(ConfigurationManager.AppSettings["Microsoft.WindowsAzure.Storage.ConnectionString"]);

            var tableClient = storageAccount.CreateCloudTableClient();
            var table = tableClient.GetTableReference("EventRegistrations");

            var operation = TableOperation.Insert(registration);
            table.Execute(operation);

            return Guid.Parse(registration.RowKey);
        }

        private void UpdateEventRegistrationCount(JToken registrationToken)
        {
            int eventId = Int32.Parse(registrationToken["Event.Id"].ToString());

            EventIncrementViewModel.IncrementEvent(eventId);
        }

        public string ToAbsoluteUrl(string relativeUrl)
        {
            if (string.IsNullOrEmpty(relativeUrl))
                return relativeUrl;

            if (HttpContext.Current == null)
                return relativeUrl;

            if (relativeUrl.StartsWith("/"))
                relativeUrl = relativeUrl.Insert(0, "~");
            if (!relativeUrl.StartsWith("~/"))
                relativeUrl = relativeUrl.Insert(0, "~/");

            var url = HttpContext.Current.Request.Url;
            var port = url.Port != 80 ? (":" + (url.Port - 1)) : String.Empty;

            return String.Format("{0}://{1}{2}{3}",
                url.Scheme, url.Host, port, VirtualPathUtility.ToAbsolute(relativeUrl));
        }
    }
}

Contoso.Events.Web/Views/Home/Event.cshtml
@model EventViewModel
@{
    ViewBag.Title = @Model.Event.Title;
}
<div class="row">
    <div class="col-sm-8">
        <h2>@Model.Event.Title</h2>
        <p>
            @Html.Raw(HttpUtility.HtmlDecode(Model.Event.Description))
        </p>
    </div>
    <div class="col-sm-4">
        <div class="well well-lg">
            @Html.ActionLink("Register Now", "Register", new { id = Model.Event.EventKey }, new { @class = "btn btn-primary btn-lg center-block" })
            <br />         
            <em>
                @Model.Event.RegistrationCount
                &nbsp;
                Attending
            </em>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="Flexible-container">
            @{
                int height = 250;
                int width = 600;
                int level = 16;
            }
            <iframe width="@width"
                    height="@height"
                    frameborder="0"
                    scrolling="no"
                    marginheight="0"
                    marginwidth="0"
                    src="http://www.bing.com/maps/embed/viewer.aspx?v=3&cp=@Model.Event.Latitude~@Model.Event.Longitude&lvl=@level&w=@width&h=@height&sty=r&typ=s&pp=&ps=55&dir=0&mkt=en-us&src=SHELL&form=BMEMJS"></iframe>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="alert alert-warning">
            <h4>
                @Model.Event.StartTime.ToLongDateString()
            </h4>
            <p>
                @Model.Event.StartTime.ToString("hh:mm tt")
                &nbsp;-&nbsp;
                @Model.Event.EndTime.ToString("hh:mm tt")
            </p>
        </div>
    </div>
</div>

Contoso.Events.Web/Views/Home/Events.cshtml
@model EventsGridViewModel
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="table-responsive">
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>Event</th>
                        <th>Date</th>
                        <th>Registrants</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Event item in Model.Events)
                    {
                        <tr>
                            <td>
                                @item.Title
                            </td>
                            <td>
                                @item.StartTime.ToShortDateString()
                            </td>
                            <td>
                                @item.RegistrationCount
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Event", new { id = item.EventKey })">
                                    Go to Event 
                                    <span class="glyphicon glyphicon-log-in"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            int numberOfPages = (int)Math.Ceiling(Model.TotalRows / (double)Model.PageSize);
            <div style="text-align: center;">
                <ul class="pagination" style="display: inline-block">
                    <li class="@(Model.CurrentPage <= 1 ? "disabled" : String.Empty)">
                        <a href="@Url.Action("Events", new { id = Model.CurrentPage - 1})">
                            <span class="glyphicon glyphicon-backward"></span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">
                            Page @Model.CurrentPage / @numberOfPages
                        </a>
                    </li>
                    <li class="@(Model.CurrentPage >= numberOfPages ? "disabled" : String.Empty)">
                        <a href="@Url.Action("Events", new { id = Model.CurrentPage + 1})">
                            <span class="glyphicon glyphicon-forward"></span>
                        </a>
                    </li>
                </ul>
            </div>
        }
    </div>
</div>

Contoso.Events.Web/Views/Home/Index.cshtml
@model UpcomingEventsViewModel
@{
    ViewBag.Title = "Home";
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('.eventsList .more').moreLink({
                showChar: 250,
                ellipsestext: "...",
                moretext: "Show More",
                lesstext: "Show Less"
            });

        });
    </script>
}
<div class="jumbotron">
    <h1>Upcoming Events</h1>
    <div class="well well-sm">
        <div class="list-group eventsList">
            @foreach (Event item in Model.Events)
            {
                <a class="list-group-item active" href="@Url.Action("Event", new { id = item.EventKey })">
                    <h3 class="list-group-item-heading">
                        @item.Title
                        @if (item.RegistrationCount > 0)
                        {
                            <span class="label label-info pull-right">
                                @item.RegistrationCount Registered
                            </span>
                        }
                        else
                        {
                            <span class="label label-danger pull-right">
                                No Registrants
                            </span>
                        }
                    </h3>
                    <small>
                        @item.StartTime.ToString("dd/MM/yy HH:mm tt")
                        &nbsp;-&nbsp;
                        @item.EndTime.ToString("dd/MM/yy HH:mm tt")
                    </small>
                    <p class="list-group-item-text more">
                        @Html.Raw(HttpUtility.HtmlDecode(item.Description))
                    </p>
                </a>
            }
        </div>
    </div>
</div>

Contoso.Events.Web/Views/Home/Register.cshtml
@model RegisterViewModel
@{
    ViewBag.Title = "Register";
}
<h3>@Model.Event.Title</h3>
<hr />
<p>
    @ViewBag.Message
</p>
<div class="well well-sm">
    @using (Html.BeginRouteForm("DefaultApi", new { controller = "Register", httproute = "true" }, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        
        @Html.HiddenFor(m => m.Event.Id)
        @Html.HiddenFor(m => m.Event.EventKey)

        @Html.EditorFor(m => m.RegistrationStub)

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </div>
    }
</div>

Contoso.Events.Web/Views/Home/Registered.cshtml
@model Guid?
<div class="jumbotron">
    <h2>
        Thanks for Registering!
    </h2>
    <p>
        Your registration Id is: <small>@Model</small>
    </p>
    <p>
        @Html.ActionLink("Go back to Event List", "Events", new { }, new { @class = "btn btn-primary btn-lg" })
    </p>
</div>

Contoso.Events.Web/Views/Shared/EditorTemplates/Int32.cshtml
@{
    IDictionary<string, object> attributes = new Dictionary<string, object>();
    if (!string.IsNullOrEmpty(ViewData.ModelMetadata.Watermark))
    {
        attributes.Add("placeholder", ViewData.ModelMetadata.Watermark);
    }

    IEnumerable<ModelValidator> validators = ModelValidatorProviders.Providers.GetValidators(ViewData.ModelMetadata, ViewContext);
    ModelClientValidationRule stringLengthRule = validators.SelectMany(v => v.GetClientValidationRules()).FirstOrDefault(m => m.ValidationType == "length");
    if (stringLengthRule != null && stringLengthRule.ValidationParameters.ContainsKey("max"))
    {
        attributes.Add("maxlength", stringLengthRule.ValidationParameters["max"]);
    }

    attributes.Add("class", "form-control");
    attributes["type"] = "number";
}
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, attributes)

Contoso.Events.Web/Views/Shared/EditorTemplates/Object.cshtml
@if (Model == null)
{
    <text>@ViewData.ModelMetadata.NullDisplayText</text>
}
else if (ViewData.TemplateInfo.TemplateDepth > 1)
{
    <text>@ViewData.ModelMetadata.SimpleDisplayText</text>
}
else
{
    <fieldset>
        @foreach (var prop in ViewData.ModelMetadata.Properties.Where(pm => pm.ShowForDisplay && !ViewData.TemplateInfo.Visited(pm)))
            {
                if (prop.HideSurroundingHtml)
                {
                    <text>@Html.Display(prop.PropertyName)</text>
                }
                else
                {
                    var inputName = "input" + prop.PropertyName;
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="@inputName">
                            @prop.GetDisplayName()
                        </label>
                        <div class="col-md-8">
                            @Html.Editor(prop.PropertyName)
                        </div>
                    </div>
                }
            }
    </fieldset>
}

Contoso.Events.Web/Views/Shared/EditorTemplates/String.cshtml
@{
    IDictionary<string, object> attributes = new Dictionary<string, object>();
    if (!string.IsNullOrEmpty(ViewData.ModelMetadata.Watermark))
    {
        attributes.Add("placeholder", ViewData.ModelMetadata.Watermark);
    }

    IEnumerable<ModelValidator> validators = ModelValidatorProviders.Providers.GetValidators(ViewData.ModelMetadata, ViewContext);
    ModelClientValidationRule stringLengthRule = validators.SelectMany(v => v.GetClientValidationRules()).FirstOrDefault(m => m.ValidationType == "length");
    if (stringLengthRule != null && stringLengthRule.ValidationParameters.ContainsKey("max"))
    {
        attributes.Add("maxlength", stringLengthRule.ValidationParameters["max"]);
    }

    attributes.Add("class", "form-control");
}
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, attributes)

Contoso.Events.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contoso Events</title>
    @Styles.Render("~/styles/css")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <span class="glyphicon glyphicon-road"></span>
                    Contoso Events
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Events", "Home")">
                            All Events <span class="glyphicon glyphicon-th"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <header>
            @RenderSection("header", required: false)
        </header>
        <article>
            @RenderBody()
        </article>
        <footer>
            <hr />
            @RenderSection("footer", required: false)
            <p>&copy; @DateTime.Now.Year - Contoso Events</p>
        </footer>
    </div>
    @Scripts.Render("~/scripts/jquery")
    @Scripts.Render("~/scripts/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>